### ISSUE TITLE
Pressure-sensitive drawing app

### ISSUE THREAD

**Issue by berlincount** [mobiscribers/mobiscribers#28]
Drawing should be pressure sensitive, as supported by the input device.

Might not allow/need undo functionality, and probably should not be vector-based, but instead a bitmap at the resolution of the display instead.

**Comment by asdf23** [comment]
It's this not already the case? I do not understand the request.

**Comment by berlincount** [comment]
What app are you talking about? Maybe I‘m not aware of it.

I‘m thinking along the lines of portrait painting and using pressure the regulate the shade ... i.e., pressure relates to grayscale. 

No need to switch tools or pick color, just draw.

**Comment by asdf23** [comment]
The notes app. It sound like you are asking for another type of pen.... You could use this existing app.. Which is pressure sensitive, I believe that you just want a airbrush tool.
You could probably find another app that does this in the meantime.

**Comment by berlincount** [comment]
Yes, this is a request for another type of App, and an Open-Source version of that.

The Mobiscribe has a unique set of capabilties, and having a simple App demonstrate those succinctly and openly would enable other developers to learn from that and build even more awesome stuff.

If you know such an App, please let me know.

**Comment by asdf23** [comment]
In the new notes you can set the color, the pen is also pressure sentitive.
