### ISSUE TITLE
nNote functionality to delete like an eraser, not connected lines

### ISSUE THREAD

**Issue by stdedos** [mobiscribers/mobiscribers#42]
Sometimes I am writing cursively. That means, however, if I want to remove a letter or two, tap-delete does not work for me (as it will erase a big portion of the written things).

Add a functionality, for a "writing eraser", so that I can remove whatever I am scribbling

**Comment by asdf23** [comment]
I noticed that after inserting a picture I could not remove any part of it. There is no "white" ink. I think that feature would solve both problems

**Comment by asdf23** [comment]
This can be closed based on the latest version of the software.
