### ISSUE TITLE
Battery drain in 2 days since 2 updates ago

### ISSUE THREAD

**Issue by ronsonntag54** [mobiscribers/mobiscribers#50]
When I first got the device and installed Kindle, I could read, hit the sleep, and go right back to reading (without first closing and then opening Kindle) and the device charge would last almost two weeks. Ever since the update from about a week ago, the device is out of charge in just TWO DAYS. And, that is with wireless turned off (before I could leave the wireless turned on).

What is the deal? This is completely unusable.

**Comment by stevecfischer** [comment]
I've been noticing the same exact thing and I'm not using Kindle at all. Just note taking

**Comment by ronsonntag54** [comment]
Looks like the latest update fixed this problem (updated yesterday).

**Comment by ronsonntag54** [comment]
Closed because MobiScribe website threads confirmed latest update fixed the problem and I have confirmed it on my device.
